language: node_js
node_js:
  - "0.8"
  - "0.10"
env:
  global:
    - BIN="node" OPTION=""
matrix:
  include:
    - node_js: "0.10"
      env: BIN="phantomjs"
    - node_js: "0.10"
      env: BIN="rhino"
    - node_js: "0.10"
      env: BIN="rhino" OPTION="-require"
    - node_js: "0.10"
      env: BIN="ringo"
    - node_js: "0.10"
      env: BIN="grunt" OPTION="saucelabs"
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "[ $BIN != 'rhino' ] || (sudo mkdir /opt/rhino-1.7R5 && sudo wget -O /opt/rhino-1.7R5/js.jar https://oss.sonatype.org/content/repositories/snapshots/org/mozilla/rhino/1.7R5-SNAPSHOT/rhino-1.7R5-20120629.144839-4.jar)"
  - "[ $BIN != 'rhino' ] || (echo -e '#!/bin/sh\\njava -jar /opt/rhino-1.7R5/js.jar $@' | sudo tee /usr/local/bin/rhino && sudo chmod +x /usr/local/bin/rhino)"
  - "[ $BIN != 'ringo' ] || (wget http://ringojs.org/downloads/ringojs-0.9.zip && sudo unzip ringojs-0.9 -d /opt && rm ringojs-0.9.zip)"
  - "[ $BIN != 'ringo' ] || (sudo ln -s /opt/ringojs-0.9/bin/ringo /usr/local/bin/ringo && sudo chmod +x /usr/local/bin/ringo)"
  - "[ $BIN != 'grunt' ] || (npm i -g grunt-cli && npm i)"
script:
  - "[ $BIN == 'grunt'] || (cd test && $BIN $OPTION ./test.js)"
  - "[ $BIN != 'grunt'] || ($BIN $OPTION)"
